blog_index:
    path:     /
    defaults: { _controller: "EurotradeBundle:blog:index" }
    methods:  GET

blog_show:
    path:     /{id}/show
    defaults: { _controller: "EurotradeBundle:blog:show" }
    methods:  GET

blog_new:
    path:     /new
    defaults: { _controller: "EurotradeBundle:blog:new" }
    methods:  [GET, POST]

blog_edit:
    path:     /{id}/edit
    defaults: { _controller: "EurotradeBundle:blog:edit" }
    methods:  [GET, POST]

blog_delete:
    path:     /{id}/delete
    defaults: { _controller: "EurotradeBundle:blog:delete" }
    methods:  DELETE
