user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

eurotrade:
    resource: "@EurotradeBundle/Resources/config/routing.yml"
    prefix:   /

eurotrade_document:
        resource: "@EurotradeBundle/Resources/config/routing/document.yml"
        prefix:   /document

eurotrade_blog:
        resource: "@EurotradeBundle/Resources/config/routing/blog.yml"
        prefix:   /blog

fos_user:
        resource: "@FOSUserBundle/Resources/config/routing/all.xml"
        prefix:   /user
