eurotrade_blog:
    resource: "@EurotradeBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

eurotrade_homepage:
    path:     /
    defaults: { _controller: EurotradeBundle:Default:index }
